<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Stripe
 */
?>
<?php
/** @var Amasty_Stripe_Block_Form_Stripe $this */
$code = $this->getMethodCode();
$visibility = $this->isIwdOpc() ? '' : 'style="display:none"';
$intendId = $this->getPaymentIntendId();
$jsonPaymentData = json_encode($this->getPaymentRequestData());
$updateUrl = $this->getUrl('amstripefront/payment/update', array('_secure' => true));
?>
<div id="payment_form_<?= $code ?>" <?= $visibility ?>>
    <div id="payment-request-button" class="stripeButton"></div>
    <div id="stripe-card-element" class="stripeCard"></div>
    <div id="stripe-card-errors" role="alert"></div>
</div>
<script>
    function initStripe() {
        var stripePaymentData = <?= $jsonPaymentData ?>;
        if (window.amStrypePayment === void 0) {
            window.amStrypePayment = new AmStripePayment(
                '<?= $this->getPublicKey() ?>',
                '<?= $code ?>',
                '<?= $this->getController() ?>',
                '<?= $intendId ?>',
                stripePaymentData,
                '<?= $updateUrl ?>'
            );
        } else {
            window.amStrypePayment.initialize(
                '<?= $this->getPublicKey() ?>',
                '<?= $code ?>',
                '<?= $this->getController() ?>',
                '<?= $intendId ?>',
                stripePaymentData,
                '<?= $updateUrl ?>'
            );
        }
    }

    if (document.readyState === 'complete') {
        initStripe();
    } else {
        document.observe('dom:loaded', initStripe);
    }
</script>
