<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package App for Payments with Stripe
*/
?>
<?php
/** @var Amasty_Stripe_Block_Form_Stripe $this */
$code = $this->getMethodCode();
?>
<div id="payment_form_<?= $code ?>" style="display:none">
    <div id="payment-request-button" class="stripeButton"></div>
    <div id="stripe-card-element" class="stripeCard"></div>
    <div id="stripe-card-errors" role="alert"></div>
</div>
<script>
    function initStripe() {
        if (window.amStrypePayment === void 0) {
            window.amStrypePayment = new AmStripePayment(
                '<?= $this->getPublicKey() ?>',
                '<?= $code ?>',
                '<?= $this->getController() ?>',
                '<?= $this->getPaymentIntendId() ?>',
                <?= json_encode($this->getPaymentRequestData()) ?>
            );
        } else {
            window.amStrypePayment.initialize(
                '<?= $this->getPublicKey() ?>',
                '<?= $code ?>',
                '<?= $this->getController() ?>',
                '<?= $this->getPaymentIntendId() ?>',
                <?= json_encode($this->getPaymentRequestData()) ?>
            );
        }
    }

    if (document.readyState === 'complete') {
        initStripe();
    } else {
        document.observe('dom:loaded', initStripe);
    }
</script>
